language: java

jdk:
  - oraclejdk8
  
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi  
  
install:
  - mvn --settings travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
  
addons:
  sonarcloud:
    organization: "nebelritter-github"
    token:
      secure: c94f0fa3231a9d614c7709d599c4308c2b6acf91
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  
  
deploy:
    -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: idealo/logback-redis
      tags: true
      jdk: oraclejdk8
    -
    provider: releases
    api_key: $GIT_HUB_O_AUTH_TOKEN
    file: dice-roller.zip
    skip_cleanup: true
    on:
      tags: true
