language: java

jdk:
  - oraclejdk8

before_install: 
 - chmod +x travis/deploy.sh
 - chmod +x travis/gpg.sh
  
addons:
  sonarcloud:
    organization: "nebelritter-github"
    token:
      secure: c94f0fa3231a9d614c7709d599c4308c2b6acf91
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn --settings travis/settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  
  
after_success:
    - travis/deploy.sh
    

