language: java

sudo: false
install: true

jdk:
  - oraclejdk8
  
addons:
  sonarcloud:
    organization: "Nebelritter"
    token:
      secure: c94f0fa3231a9d614c7709d599c4308c2b6acf91
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  
  
deploy:
  provider: releases
  api_key: $GIT_HUB_O_AUTH_TOKEN
  file: dice-roller.zip
  skip_cleanup: true
  on:
    tags: true
